### PR TITLE
Fix some typos in libimobiledevice

### PR DESCRIPTION
**Pull request by corsac-s**
Hi,

Here are some fixes for typos inside libimobiledevice code (error messages, manpages, comments etc.).

### CODE REVIEW

**Comment by Blefish** [comment]
Maybe this fits into one commit?

**Comment by corsac-s** [comment]
Sure, I can squash them if you prefer

**Comment by corsac-s** [comment]
@nikias what would you prefer?

**Comment by corsac-s** [comment]
@nikias what would you prefer?

**Comment by corsac-s** [comment]
@nikias what would you prefer?

**Comment by corsac-s** [comment]
Nikias what would you prefer?

**Comment by corsac-s** [comment]
Trying with a notification to @nikias

**Comment by corsac-s** [comment]
Any news on this PR?

**Comment by nikias** [comment]
Merged after rebase. Thanks.

**Pull request closed without merging**
