### PR TITLE
Add idevicelocation tool

### PR DESCRIPTION
**Pull request by robbertvanginkel**
Set device location for specified lat/long on an attached device.

Usage:
```
  $ idevicelocation <lat> <long>
  $ idevicelocation --stop
```
Uses `com.apple.dt.simulatelocation`/`DTSimulateLocation` from the
developer disk image under the hood.

### CODE REVIEW

**Comment by nudge** [comment]
This is amazing. Fantastic work Robbert!

**Comment by Dantee296** [comment]
Hi can you tell me how to enable GPS (Location Services) remotely 
can we use this tool to enable it ?

**Comment by nghiadhd** [comment]
@Dantee296 
I must run XCUITest script to turn on LocationService before do simulate location

**Comment by nghiadhd** [comment]
@robbertvanginkel 
Seem 'idevicelocation --stop' doesn't work. It doesn't switch back to GPS location

**Comment by Dantee296** [comment]
@nghiadhd  u mean automation using appium

**Comment by nghiadhd** [comment]
@Dantee296 
You can use Appium or just write a XCUITest script and use xcodebuild test to run this script

**Comment by daniel-bluesea** [comment]
what is the format of <lat> <long>?
what is the impact on the attached device?

**Comment by umutuzgur** [comment]
Awesome PR! Any reason why this is not being merged?

**Comment by c00ni** [comment]
@nghiadhd It does reset location, it just might take a minute.

**Comment by nghiadhd** [comment]
@truonggiang0710 
I don't check location status, I just get location by my MAC and set it into the device before actually call stopping
That is fast way than stop

**Comment by truonggiang0710** [comment]
Hi @nghiadhd , thanks for your reply. Do we have any way to enable/disable location service in Setting on iPhone ?

**Comment by nikias** [comment]
Hi, I had this lying around on my disk since some time back in 2016. I just pushed it to git. I called it `idevicesetlocation` and the usage is slightly different.

**Pull request closed without merging**
