### PR TITLE
Fix iOS 5 SSL error

### PR DESCRIPTION
**Pull request by tihmstar**
Set SSL_OP_IGNORE_UNEXPECTED_EOF on OpenSSL 3 to fix talking to iOS 5

### CODE REVIEW

**Comment by mexmer** [comment]
fix checking openssl version
in older versions, there is no OPENSSL_VERSION_MAJOR macro, use
```
#if OPENSSL_VERSION_NUMBER >= 0x030000000
```
instead

**Comment by nikias** [comment]
Turns out that `SSL_CTX_set_options` does *not* clear options that have been set before, so I could solve this even more elegantly: a15a31611d61379297ec45c2a5d34ab57dfb958d

**Comment by mexmer** [comment]
@nikias i would still not use OPENSSL_VERSION_MAJOR macro, it's bad practice to compare undefined macro value, while most preprocessors simple replace undefined macro with empty value, it's just not right

**Comment by nikias** [comment]
@mexmer fair enough: 9a5e78fe56267d6c721c92055c3ae9702bd25871

**Pull request closed without merging**
