### PR TITLE
Allow get/put folders from/to devices.

### PR DESCRIPTION
**Pull request by tomriddly**
The original implementation of `get` and `put` of `afcclient` supports only single file. This PR make it work for directories.

### CODE REVIEW

**Comment by tomriddly** [comment]
@nikias would you please check if there is further more working or ready for merge?

**Comment by nikias** [comment]
Looks good from what I can tell from my phone, but could you
a) use tabs instead of spaces to keep the original formatting intact
b) prefix the 2 commit messages with `afclient: ` followed by the original message (omitting 'afcclient')
(the 3rd commit for .gitignore is fine)

**Comment by tomriddly** [comment]
> Looks good from what I can tell from my phone, but could you a) use tabs instead of spaces to keep the original formatting intact b) prefix the 2 commit messages with `afclient: ` followed by the original message (omitting 'afcclient') (the 3rd commit for .gitignore is fine)

Done. Commit style and code style are changed

**Comment by mexmer** [comment]
i would suggest adding -r for recursive push/pull, and disable recursive by default. it's common practice for many other commandline copying tools also.

**Comment by tomriddly** [comment]
> i would suggest adding -r for recursive push/pull, and disable recursive by default. it's common practice for many other commandline copying tools also.

`(s)cp` and `zip` do need a `-r` option indeed. But on the other hand, `adb pull/push` will do the transper no matter from a folder or file, which I thought could be the same behaviour of afcclient. I just feel it would be easy to use as what adb has done. Would it be any unforseen risk if we do recursive as default?

**Comment by nikias** [comment]
I don't mind without a -r option, but let's make sure that maybe we don't overwrite existing directories. The same actually goes for files, you could easily break your device...

**Comment by nikias** [comment]
Yes -f makes sense. Without it and existing we should abort with an error message.

**Comment by mexmer** [comment]
> > i would suggest adding -r for recursive push/pull, and disable recursive by default. it's common practice for many other commandline copying tools also.
> 
> `(s)cp` and `zip` do need a `-r` option indeed. But on the other hand, `adb pull/push` will do the transper no matter from a folder or file, which I thought could be the same behaviour of afcclient. I just feel it would be easy to use as what adb has done. Would it be any unforseen risk if we do recursive as default?

it's not just cp and zip, abd is rather exception, than "good example". in linux most tools that manipulate files in commandline require -r (some -R) to do recursive work.

adb is bad example for two reasons, major one is, that it does follow symlinks, and doesn't prevent cycling trough links (unless they fixed that, but that bug has been there for years), second is, that it has flawed long path handling (again, unless they fixed it over years)

as for overwrite, i agree that -f (or --force) is good choice.

**Comment by tomriddly** [comment]
> > > i would suggest adding -r for recursive push/pull, and disable recursive by default. it's common practice for many other commandline copying tools also.
> > 
> > 
> > `(s)cp` and `zip` do need a `-r` option indeed. But on the other hand, `adb pull/push` will do the transper no matter from a folder or file, which I thought could be the same behaviour of afcclient. I just feel it would be easy to use as what adb has done. Would it be any unforseen risk if we do recursive as default?
> 
> it's not just cp and zip, abd is rather exception, than "good example". in linux most tools that manipulate files in commandline require -r (some -R) to do recursive work.
> 
> adb is bad example for two reasons, major one is, that it does follow symlinks, and doesn't prevent cycling trough links (unless they fixed that, but that bug has been there for years), second is, that it has flawed long path handling (again, unless they fixed it over years)
> 
> as for overwrite, i agree that -f (or --force) is good choice.

symlinks cycling is what I've never considered, which makes `-r` may be a necessary option.
I made some updates to support `-r` and `-f`, and fix the docs and help messages.

**Comment by mexmer** [comment]
thanks you, looks good to me.

**Comment by tomriddly** [comment]
@nikias I've run local test and did not find any issue. Could this be merged?

**Comment by nikias** [comment]
I pushed the commits with some small changes, merging the coding style fixes directly into the initial commits and prevent later code-style hiccups. Could you please check with latest commit if this works properly now?

**Comment by tomriddly** [comment]
line 916, additional `argc` check for `get` is missing:
```C
else {
	printf("Error: Invalid number of arguments\n");
	return;
}
```
The other changes seem appropriate to me。

**Comment by nikias** [comment]
See 9ccc52222c287b35e41625cc282fb882544676c6.

**Pull request closed without merging**
