### PR TITLE
Improve usage of gnutls library

### PR DESCRIPTION
**Pull request by nmav**

### CODE REVIEW

**Comment by nikias** [comment]
Have you checked if this works with older devices/iOS versions?

**Comment by nmav** [comment]
No. However, this change shouldn't affect older devices or iOS versions. TLS1.0 and AES (the ciphers in the previous string) are enabled by the gnutls_set_default_priority().

**Comment by mexmer** [comment]
since autonegotiation with TLS 1.2 enabled breaks compatibility with elder iOS devices, i believe this will do so also. @nmav please retest your solution with iOS device running iOS 5 or lower.

**Comment by nmav** [comment]
Hmmm, in that case I withdraw that part of the patch. Let's handle it when the time comes.

**Comment by mexmer** [comment]
@nmav you might wait for saurik to retest. i compile libimobile and related stuff against openssl, so can't test your stuff without completely rebuilding everything.

**Comment by nikias** [comment]
Merged to master after rebase.

**Pull request closed without merging**
