### PR TITLE
idevicecrashreport: Filter crash reports by filename

### PR DESCRIPTION
**Pull request by fr0l**
Allows to filter crash reports by filename and copy only matching crash reports.

```bash
idevicecrashreport -u 00008020-001234 --filter MyApplication crash_reports

Move: /MyApplication-2019-07-29-164320.ips
```

This allows significantly improve speed of collecting only required crash reports.

And addresses changes in PR # 591

### CODE REVIEW

**Comment by fr0l** [comment]
Hey @nikias , please could you take a look? Thank you!

**Comment by LaikaN57** [comment]
Linking to #591 as the OP did not catch the PR identifier properly.

**Comment by darshilgada24** [comment]
Any plans to release this change?

**Comment by nikias** [comment]
Merged with ec932860bb6abb86e05e64935568c3678ca9b878.

**Pull request closed without merging**
