### PR TITLE
Update idevicebackup2.c to Support Newly Added AFC Files

### PR DESCRIPTION
**Pull request by Lakr233**
See the code for details.

### CODE REVIEW

**Comment by mexmer** [comment]
just curious, where did you see those files?
i just did backup of my ipad (ios 16.6), and i have there only these files
image
files listed in that array are stored inside info.plist (that is located inside itunes backup folder)
there is no need to store every file you locate trough afc.
still there might be difference in setting of yours and my device, that might cause inclusion this files to backup, so if you can check your info.plist for these files, if they are there, share some details about your device settings (like if it's using icloud synchronization and such, also version of ios)

**Comment by Lakr233** [comment]
I discovered the files through Finder backup while working on my wireless backup robot project. After confirming their presence, I decided to include them in the project. fyi: iOS 16.5, macOS 13.5.1 (22G90), https://github.com/Lakr233/BBackupp

截屏2023-08-20 22 02 01

**Comment by mexmer** [comment]
if you look trough AFC to phone filesystem, there is lot of files, but many of them are recreated either upon restore or by running itunes, photos or other system app, that's why i'm saying not everything is needed to backup, because phone os will recreate it.

since these files are inside **info.plist**, then they should be added as you say, to have them properly restored.
good find

**Review by mexmer — APPROVED** [review]

**Comment by mexmer** [comment]
btw. i just checked code of our application and we have compiled following list of files found in info.plist (not all are listed in idevicebackup, and probly some of them were valid for old version of itunes, but are not required for new version), i just didn't bother to compare it to list in libimobile.

```
				"IC-Info.sidb",
				"IC-Info.sidv",
				"VoiceMemos.plist",
				"iTunesPlaylists",
				"iTunesPodcasts",
				"iTunesMovies",
				"iTunesMoviePlaylists",
				"iTunesTVShows",
				"iTunesTVShowPlaylists",
				"iTunesRingtones",
				"iTunesApplicationIDs",
				"iPhotoAlbumPrefs"
				"ApertureAlbumPrefs",
				"PhotosAppAlbumPrefs",
				"PSAlbumAlbums",
				"PSElementsAlbums",
				"PSFolderAlbums",
				"PhotosFolderAlbums",
				"PhotosFolderName",
				"PhotosFolderPrefs",
				"iTunesPrefs",
				"iTunesPrefs.plist",
```

**Comment by Lakr233** [comment]
That would be 

```
                "ApertureAlbumPrefs",
                "IC-Info.sidb",
                "IC-Info.sidv",
                "PSAlbumAlbums",
                "PSElementsAlbums",
                "PSFolderAlbums",
                "PhotosAppAlbumPrefs",
                "PhotosFolderAlbums",
                "PhotosFolderName",
                "PhotosFolderPrefs",
                "VoiceMemos.plist",
                "iPhotoAlbumPrefs",
                "iTunesApplicationIDs",
                "iTunesMoviePlaylists",
                "iTunesMovies",
                "iTunesPlaylists",
                "iTunesPodcasts",
                "iTunesPrefs",
                "iTunesPrefs.plist",
                "iTunesRingtones",
                "iTunesTVShowPlaylists",
                "iTunesTVShows",
```

**Pull request closed without merging**
