### PR TITLE
src: Update for LibreSSL >= 3.5.0

### PR DESCRIPTION
**Pull request by orbea**
This fixes the build with LibreSSL `>= 3.5.0` and updates it for LibreSSL `>=3.6.0`.

### CODE REVIEW

**Comment by nikias** [comment]
This won't do. We still need to support the older versions of LibreSSL. Instead of removing stuff we need to add the right version checks if the feature is already available in LibreSSL/OpenSSL.

**Comment by orbea** [comment]
> This won't do. We still need to support the older versions of LibreSSL.

Thanks for the prompt reply, give me some time and I will update this PR.

**Comment by orbea** [comment]
@nikias I updated PR, it was not as much effort as I imagined. I am unsure about the init/deinit code paths and they do not seem to be causing problems so I left them alone.

**Comment by orbea** [comment]
@nikias When you have a chance can you please review this PR?

**Comment by nikias** [comment]
Merged with d87213038d0a428adb3e91432a1b7f6ae4817993.

**Pull request closed without merging**
