### PR TITLE
Fetching IOKit tree via idevicediagnostics ioreg failing on iOS 9.1, …

### PR DESCRIPTION
**Pull request by rgadbois**
…but works by entry

### CODE REVIEW

**Comment by nikias** [comment]
@rgadbois Can you redo the pull request with correct indentation using tabs instead of spaces? Thanks.

**Comment by reidhoch** [comment]
Are we still waiting on this to be fixed?

**Comment by daniel-bluesea** [comment]
@nikias @rgadbois can we still retrieve the IODeviceTree or is it obsolete? 
do we have a "new name" for it for the new ioregentry command?

**Comment by progressnerd** [comment]
Did it ever work by plane alone? Also, I believe if you're matching by Class or Name that a Plane is optional, like this API:
  https://developer.apple.com/documentation/installerjs/ioregistry/1812186-matchingclass
  https://developer.apple.com/documentation/installerjs/ioregistry/1812200-matchingname

I'm thinking one ioreg command with flags for class, name, and plane.

**Comment by nikias** [comment]
I merged this with correct indentation and some small cosmetic changes.

**Comment by progressnerd** [comment]
Unfortunately, this change offers no way to query by entry class, like IOPMPowerSource.

**Pull request closed without merging**
