### PR TITLE
add erase function

### PR DESCRIPTION
**Pull request by zytzjx**
Erase All Content and Settings

### CODE REVIEW

**Comment by Blefish** [comment]
Make sure result_code is set, also check the error of mobilebackup2_send_message, it can fail if device is not activated.

**Comment by Blefish** [comment]
Yes, I missed that.

I meant that when you currently send this command, the process returns 255, I guess it should be 0.

**Comment by jginsburgn** [comment]
Why has this PR not been merged?

**Comment by Blefish** [comment]
Maybe this is not the right place for it. It's the easiest to add the code for it here, but idevicebackup2 does not represent wiping in any meaningful way :).

**Comment by nikias** [comment]
Yes. It doesn't belong there. Too many users will lose data because they expect this is a backup tool. There's no need for a mainstream tool like this
IMO. Closing it for now.

**Pull request closed without merging**
