### PR TITLE
fix openssl 3.0 internal error when read timeout

### PR DESCRIPTION
**Pull request by pudge62**
The timeout in `internal_ssl_read` results in a  fatal error in openssl 3.0 by default. We can change this behaviour by adding flag `SSL_OP_IGNORE_UNEXPECTED_EOF `.

Similar Issues in other projetcs:
- [[nginx] SSL: use of the SSL_OP_IGNORE_UNEXPECTED_EOF option.](https://www.mail-archive.com/nginx-devel@nginx.org/msg10938.html)
- [krb5 commit: Fix k5tls module for OpenSSL 3](https://mailman.mit.edu/pipermail/cvs-krb5/2021-June/015298.html)

How to Reproduce:

1、 link libimobiledevice with openssl 3.0
2、start idevicedebugserverproxy
```bash
idevicedebugserverproxy -d -u xxxxx 1234
```
3、start lldb
```bash
(lldb) platform select remote-ios
(lldb) platform connect connect://127.0.0.1:1234
error: failed to get reply to handshake packet
```
Expected Result:
`platform connect` command in lldb can complete successfully

### CODE REVIEW

**Comment by hiepnh0** [comment]
Thanks

**Comment by PsychoTea** [comment]
This PR also fixes an issue affecting devices on iOS 15, when compiling with openssl3, where `idevicesyslog` will print a small number of messages before "hanging" and not printing any further messages. Thanks @pudge62!

**Comment by nikias** [comment]
@pudge62 would you mind sending me your full name so I can properly credit you? Thanks. You can reach out to me on telegram (@pimskeks) or find my email in the commit logs.

**Comment by pudge62** [comment]
> @pudge62 would you mind sending me your full name so I can properly credit you? Thanks. You can reach out to me on telegram (@pimskeks) or find my email in the commit logs.

I have changed the author name to my real name.

**Comment by nikias** [comment]
Merged after rebase with 32d531a.

**Pull request closed without merging**
