### PR TITLE
Fixed method visbility in Cython bindings, Python2/3 compatibility

### PR DESCRIPTION
**Pull request by wendyisgr33n**

### CODE REVIEW

**Comment by wendyisgr33n** [comment]
Any thoughts on these changes?

**Comment by nikias** [comment]
@wendyisgr33n would you have a real name for me so I can credit you properly in the commit logs?

**Comment by wendyisgr33n** [comment]
@nikias You can just use wendyisgr33n - thanks for taking a look at this!

**Comment by nikias** [comment]
Merged after rebase.

**Pull request closed without merging**
