### PR TITLE
check return value for "asprintf", eliminate compiler warnnings

### PR DESCRIPTION
**Pull request by chenbd**
this commit eliminate compiler warnings about asprintf, the check the return value for asprintf.

### CODE REVIEW

**Comment by Tatsh** [comment]
You should not cast the return value of `strlen()` for the `asprintf()` calls. The return value type from `strlen()` is `size_t` which is not `int`, it is `unsigned int` (see `man stddef.h`). The other lines cast because the original data type is `int` and to get rid of warnings (arguably the data type for `pkt_len` should be `unsigned int` so the casts can be removed).

The warning you are getting from the formatting functions like `asprintf()` without the cast is telling you to use `%u`, not to cast the value.

```c
void f() {
    ret = asprintf(&prefix, ",%u,%u,", strlen(argv[i]) * 2, i);
}
```

**Comment by chenbd** [comment]
yes, The return value type from strlen() is size_t. but size_t is unsigned int only on 32 bit systems in my opinion. 

so on my 64bit system the warning is:
debugserver.c:571:3: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'size_t' [-Wformat=]
   ret = asprintf(&prefix, ",%u,%d,", strlen(argv[i]) * 2, i);

**Comment by Tatsh** [comment]
Yes the width is different on 32-bit vs 64-bit. It should be 32-bit on 32-bit systems and 64-bit on 64-bit systems, although this is not a guarantee either. So I am changing my mind and saying to cast in this case, because having an `#ifdef` for 64-bit vs 32-bit is lame when it's only a call to `asprintf` and the return value from `strlen` will not exceed the limit of `unsigned int` on 32-bit or 64-bit. I wish there was a better way without casting and not using preprocessor macros.

**Comment by neheb** [comment]
%zu ?

**Comment by nikias** [comment]
Merged with 94ed8c464dee51191f16b5758f090e920fb4d3e1.

**Comment by Tatsh** [comment]
Even if 5 years later, great.

**Comment by nikias** [comment]
@Tatsh hahahahaha :) sorry took some time to review it 🤣

**Pull request closed without merging**
